export const typesProduct = {
  // PRODUCTS
  FETCH_PRODUCTS_START: "FETCH_PRODUCT_START",
  FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCT_SUCCESS",
  FETCH_PRODUCTS_ERROR: "FETCH_PRODUCT_ERROR",

  // PRODUCT
  FETCH_PRODUCT_DETAILS_START: "FETCH_PRODUCT_DETAILS_START",
  FETCH_PRODUCT_DETAILS_SUCCESS: "FETCH_PRODUCT_DETAILS_SUCCESS",
  FETCH_PRODUCT_DETAILS_ERROR: "FETCH_PRODUCT_DETAILS_ERROR",
  FETCH_PRODUCT_DETAILS_RESET: "FETCH_PRODUCT_DETAILS_RESET",
};
